// Run with: node --env-file=.env.local scripts/seed-places.mjs
import { createClient } from '@sanity/client'

const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET,
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
})

let _k = 0
const key = () => `k${++_k}${Math.random().toString(36).slice(2, 6)}`
const h3 = (text) => ({
  _type: 'block', _key: key(), style: 'h3', markDefs: [],
  children: [{ _type: 'span', _key: key(), text, marks: [] }],
})
const p = (text) => ({
  _type: 'block', _key: key(), style: 'normal', markDefs: [],
  children: [{ _type: 'span', _key: key(), text, marks: [] }],
})
const li = (text) => ({
  _type: 'block', _key: key(), style: 'normal', listItem: 'bullet', level: 1, markDefs: [],
  children: [{ _type: 'span', _key: key(), text, marks: [] }],
})

const places = [
  {
    _id: 'place-montevideo',
    _type: 'place',
    title: 'Montevideo y Área Metropolitana',
    slug: { _type: 'slug', current: 'montevideo' },
    region: 'Montevideo',
    tagline: 'La capital vibrante con todo al alcance',
    placeholderGradient: 'linear-gradient(135deg, #1A4B8C 0%, #0D1F3C 100%)',
    costOfLiving: 3,
    urbanRural: 5,
    population: 5,
    facts: [
      h3('Vida en la ciudad'),
      p('Capital y ciudad más grande de Uruguay, hogar de 1.4 millones de personas — la mitad del país. Es también el hub regional de startups, coworkings y la comunidad expat más activa del país.'),
      h3('Costo de vida'),
      li('Alquiler 1 dormitorio en Pocitos o Palermo: USD 400–700/mes'),
      li('En Cordón, Buceo o Tres Cruces: USD 280–450/mes'),
      li('Comida en restaurante local: USD 6–12 por persona'),
      li('Supermercado (persona sola): USD 200–300/mes'),
      h3('Conectividad y trabajo'),
      li('Fibra óptica en toda la ciudad (ANTEL, Claro, Movistar)'),
      li('Coworkings: Punch Cowork, La Maquinista, Sinergia, Basta, BeeHive'),
      li('Régimen fiscal territorial: ingresos del exterior generalmente no se gravan durante los primeros años'),
      h3('Barrios populares para nomads'),
      li('Pocitos: hub expat, cerca del mar, servicios completos'),
      li('Palermo: bohemio y artístico, bares y cafeterías'),
      li('Ciudad Vieja: histórico, coworkings, cercanía al puerto'),
      li('Punta Carretas: upscale, shopping, tranquilo'),
      h3('Salud y servicios'),
      p('Sistema de mutualistas (salud privada) más completo del país. CASMU, Médica Uruguaya, MP, entre otras. Red de buses STM cubre toda la ciudad; bicicletas públicas MiDi disponibles.'),
    ],
    links: [
      { _key: key(), label: 'Punch Cowork', category: 'coworking', url: 'https://maps.app.goo.gl/punch-cowork' },
      { _key: key(), label: 'La Maquinista', category: 'coworking', url: 'https://maps.app.goo.gl/la-maquinista' },
      { _key: key(), label: 'Café Bacacay', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-bacacay' },
      { _key: key(), label: 'Café Roldós', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-roldos' },
    ],
  },
  {
    _id: 'place-punta-del-este',
    _type: 'place',
    title: 'Punta del Este',
    slug: { _type: 'slug', current: 'punta-del-este' },
    region: 'Maldonado',
    tagline: 'El glamour del Atlántico, playa todo el año',
    placeholderGradient: 'linear-gradient(135deg, #0093E9 0%, #1A4B8C 100%)',
    costOfLiving: 5,
    urbanRural: 4,
    population: 3,
    facts: [
      h3('El destino premium'),
      p('El balneario más glamoroso de Sudamérica, conocido internacionalmente. Temporada alta (diciembre–marzo): ambiente cosmopolita, precios multiplicados por 3–4x y una energía difícil de encontrar en otro lugar del cono sur.'),
      h3('Costo de vida'),
      li('Temporada alta: alquiler USD 2,000–5,000/mes'),
      li('Fuera de temporada (abril–noviembre): USD 500–1,200/mes'),
      li('Gastronomía: de las más caras del país'),
      li('Off-season el costo baja significativamente — muchos nomads aprovechan esto'),
      h3('Trabajo remoto'),
      li('Buena fibra en zonas residenciales'),
      li('Daimon Cowork y espacios de trabajo disponibles fuera de temporada'),
      li('La ciudad se vacía en invierno: silencio, productividad, precios bajos'),
      h3('Playas y estilo de vida'),
      li('Playa Brava: La Mano icónica, surf, kitesurf'),
      li('Playa Mansa: familia, deportes acuáticos tranquilos'),
      li('José Ignacio: lujo boutique, 30 min en auto'),
      li('Golf, polo, tenis: infraestructura deportiva de primer nivel'),
      h3('Perfil ideal'),
      p('Freelancers de alto ingreso, entrepreneurs y quienes buscan lifestyle premium en temporada. O los que quieren vivir en un balneario vacío y barato en invierno.'),
    ],
    links: [
      { _key: key(), label: 'Daimon Cowork', category: 'coworking', url: 'https://maps.app.goo.gl/daimon-cowork' },
      { _key: key(), label: 'La Bourgogne Café', category: 'cafe', url: 'https://maps.app.goo.gl/la-bourgogne' },
    ],
  },
  {
    _id: 'place-colonia',
    _type: 'place',
    title: 'Colonia del Sacramento',
    slug: { _type: 'slug', current: 'colonia-del-sacramento' },
    region: 'Colonia',
    tagline: 'Historia colonial a 50 minutos de Buenos Aires',
    placeholderGradient: 'linear-gradient(135deg, #C8940F 0%, #7A5200 100%)',
    costOfLiving: 3,
    urbanRural: 3,
    population: 2,
    facts: [
      h3('Una ciudad única'),
      p('Ciudad colonial Patrimonio UNESCO con 26.000 habitantes. Adoquines, faros y vistas al Río de la Plata. Ritmo lento, arquitectura hermosa, y una conexión diaria en ferry a Buenos Aires.'),
      h3('Costo de vida'),
      li('Alquiler apartamento: USD 300–500/mes'),
      li('Casa con jardín: USD 400–700/mes'),
      li('Gastronomía de calidad a precios razonables'),
      li('Servicios similares a Montevideo pero más tranquilo'),
      h3('Conectividad'),
      li('Fibra básica disponible; velocidad menor que Montevideo'),
      li('Buenos cafés con WiFi en el área turística'),
      li('Ferry diario a Buenos Aires: 1h en Seacat/Buquebus'),
      h3('Entorno y vida'),
      li('Viñedos y bodegas en Carmelo: 1h en auto'),
      li('Playa del Río, kayak y ciclismo'),
      li('Comunidad expat pequeña pero creciente'),
      li('Ideal para familias que quieren huir de la ciudad sin perder servicios'),
      h3('Gastronomía'),
      p('Buena escena de restaurantes con influencia rioplatense y europea. El barrio histórico concentra los mejores cafés y bares con vista al río.'),
    ],
    links: [
      { _key: key(), label: 'Café de los Faroles', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-faroles' },
      { _key: key(), label: 'El Drugstore', category: 'cafe', url: 'https://maps.app.goo.gl/el-drugstore' },
    ],
  },
  {
    _id: 'place-centro-sur',
    _type: 'place',
    title: 'Centro Sur',
    slug: { _type: 'slug', current: 'centro-sur' },
    region: 'Florida · San José · Durazno · Trinidad',
    tagline: 'El corazón agrícola y el Uruguay más auténtico',
    placeholderGradient: 'linear-gradient(135deg, #2E7D52 0%, #1d5e3a 100%)',
    costOfLiving: 2,
    urbanRural: 2,
    population: 2,
    facts: [
      h3('El Uruguay profundo'),
      p('Cuatro ciudades pequeñas en el corazón agrícola del país. El Uruguay más auténtico: gaucho, campo, carnaval local, fútbol de barrio, y comunidades unidas. Sin turismo masivo, sin precios inflados.'),
      h3('Costo de vida'),
      li('Alquiler: USD 150–300/mes (de los más bajos del país)'),
      li('Comida y servicios muy económicos'),
      li('Transporte público a Montevideo: USD 5–8 por viaje'),
      h3('Conectividad a Montevideo'),
      li('Florida: 1h en ómnibus o auto'),
      li('San José: 1h 15min'),
      li('Durazno: 2h'),
      li('Trinidad (Flores): 2h 30min'),
      h3('Vida local'),
      li('Florida: piscinas municipales, clubes deportivos, feria semanal'),
      li('San José: producción lechera y ajo, mercado local activo'),
      li('Durazno: ciudad sobre el Río Yi, pesca y camping popular'),
      li('Trinidad: capital de Flores, muy tranquila, agropecuaria'),
      h3('Perfil ideal'),
      p('Quienes quieren integrarse completamente a la vida uruguaya, trabajar remoto a bajo costo, y vivir sin comunidad expat — lo cual es tanto un desafío como una ventaja.'),
    ],
    links: [],
  },
  {
    _id: 'place-este',
    _type: 'place',
    title: 'Este — Costa de Rocha',
    slug: { _type: 'slug', current: 'este-costa-de-rocha' },
    region: 'Rocha · Lavalleja · Treinta y Tres',
    tagline: 'Costa salvaje, naturaleza sin filtros y vida lenta',
    placeholderGradient: 'linear-gradient(135deg, #1d5e3a 0%, #0D1F3C 100%)',
    costOfLiving: 2,
    urbanRural: 2,
    population: 2,
    facts: [
      h3('La costa más salvaje'),
      p('La región este incluye la costa más virgen de Uruguay. Cabo Polonio, Punta del Diablo, La Paloma, La Pedrera y Aguas Dulces son destinos únicos a nivel mundial por su naturaleza sin intervención masiva.'),
      h3('Costo de vida'),
      li('Alquiler off-season en La Paloma o La Pedrera: USD 200–400/mes'),
      li('Rocha ciudad: USD 180–350/mes'),
      li('Temporada alta (dic–feb): precios suben significativamente en la costa'),
      h3('Destinos clave'),
      li('Cabo Polonio: sin electricidad pública, lobos marinos, dunas, acceso en tractor'),
      li('Punta del Diablo: pequeño, artesanal, surf, atardecer mágico'),
      li('La Paloma: balneario con servicios, faro, windsurf'),
      li('Quebrada de los Cuervos (Treinta y Tres): cañón y reserva natural'),
      h3('Conectividad'),
      li('Rocha ciudad: fibra básica, para trabajo remoto funcional'),
      li('La Paloma: WiFi en cafés, conexión variable'),
      li('Zonas costeras aisladas: conectividad muy limitada o nula'),
      h3('Perfil ideal'),
      p('Artistas, surf, slow life, escritores y freelancers que priorizan la naturaleza y el ritmo lento. Temporada baja es el mejor momento: todo abierto, sin turistas.'),
    ],
    links: [
      { _key: key(), label: 'Café del Puerto (La Paloma)', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-del-puerto-paloma' },
    ],
  },
  {
    _id: 'place-litoral-sur',
    _type: 'place',
    title: 'Litoral Sur',
    slug: { _type: 'slug', current: 'litoral-sur' },
    region: 'Colonia Interior · Soriano · Río Negro',
    tagline: 'Río Uruguay, vino y vida gaucha auténtica',
    placeholderGradient: 'linear-gradient(135deg, #2E7D52 0%, #4A6280 100%)',
    costOfLiving: 1,
    urbanRural: 2,
    population: 2,
    facts: [
      h3('Región vitivinícola y ribereña'),
      p('El río Uruguay define esta región. Carmelo es la capital del vino uruguayo (Tannat), Mercedes y Fray Bentos son las ciudades principales sobre el río, con historia industrial y gaucha profunda.'),
      h3('Costo de vida'),
      li('De los más bajos del país: alquiler USD 120–250/mes'),
      li('Comida y servicios muy económicos'),
      li('El dólar rinde mucho aquí'),
      h3('Destinos clave'),
      li('Carmelo: capital del vino, bodegas, golf, cercanía a Buenos Aires por ferry'),
      li('Mercedes (Soriano): ciudad animada sobre el río, carnaval de tradición'),
      li('Fray Bentos (Río Negro): Museo de la Revolución Industrial UNESCO'),
      li('Young y Nuevo Berlín: pueblos chicos de influencia inmigrante europea'),
      h3('Actividades'),
      li('Río Uruguay: pesca, playa de río, navegación en verano'),
      li('Turismo rural y estancias'),
      li('Producción de vino: bodegas abiertas todo el año en Carmelo'),
      h3('Perfil ideal'),
      p('Quienes buscan el costo de vida más bajo posible, naturaleza, y una vida pausada y auténtica sin presencia turística.'),
    ],
    links: [
      { _key: key(), label: 'Café del Parque (Mercedes)', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-del-parque-mercedes' },
    ],
  },
  {
    _id: 'place-litoral-norte',
    _type: 'place',
    title: 'Litoral Norte',
    slug: { _type: 'slug', current: 'litoral-norte' },
    region: 'Paysandú · Salto · Artigas',
    tagline: 'Termas, ciudades reales y precios increíbles',
    placeholderGradient: 'linear-gradient(135deg, #C8940F 0%, #e07b39 100%)',
    costOfLiving: 1,
    urbanRural: 3,
    population: 3,
    facts: [
      h3('Las ciudades del norte'),
      p('Salto es la segunda ciudad del Uruguay (100.000 hab.) y uno de los mejores destinos del país para vivir a bajo costo con buena calidad de vida. Paysandú es la ciudad universitaria y cultural del litoral.'),
      h3('Costo de vida'),
      li('Salto: alquiler USD 180–350/mes'),
      li('Paysandú: USD 150–300/mes'),
      li('Artigas: USD 100–200/mes'),
      li('Costo de vida general muy bajo, especialmente comparado con Montevideo'),
      h3('Las termas de Salto'),
      li('Termas del Daymán: complejo termal a 8km de la ciudad, con hoteles y camping'),
      li('Termas del Arapey: más aisladas, ambiente natural, aguas de 40°C'),
      li('Acceso anual, muy económico para residentes'),
      h3('Clima y naturaleza'),
      li('Subtropical: veranos muy calurosos (35–40°C), ideales para el río'),
      li('Río Uruguay: playas de río, pesca, deportes acuáticos'),
      li('Inviernos suaves y cortos'),
      h3('Conectividad'),
      li('Fibra disponible en Salto y Paysandú'),
      li('Ómnibus a Montevideo: 4–5h (Salto), 3h (Paysandú)'),
      li('Aeropuerto en Salto con vuelos domésticos a Montevideo'),
      h3('Artigas y la frontera'),
      p('Artigas en la frontera con Brasil: ciudad pequeña, bilingüe por influencia brasuca, mercado libre de intercambio con Quaraí.'),
    ],
    links: [
      { _key: key(), label: 'Cowork Salto', category: 'coworking', url: 'https://maps.app.goo.gl/cowork-salto' },
      { _key: key(), label: 'Café Tienda Nueva (Paysandú)', category: 'cafe', url: 'https://maps.app.goo.gl/cafe-paysandu' },
    ],
  },
  {
    _id: 'place-norte',
    _type: 'place',
    title: 'Norte',
    slug: { _type: 'slug', current: 'norte' },
    region: 'Tacuarembó · Rivera · Melo',
    tagline: 'El interior profundo, Rivera fronteriza y el alma gaucha',
    placeholderGradient: 'linear-gradient(135deg, #2E7D52 0%, #1A4B8C 100%)',
    costOfLiving: 1,
    urbanRural: 2,
    population: 2,
    facts: [
      h3('El norte profundo'),
      p('La región más interior y auténtica del Uruguay. Tacuarembó es la capital gaucha; Rivera es una ciudad fronteriza única con libre circulación con Brasil; Melo es la puerta al interior más remoto.'),
      h3('Costo de vida'),
      li('El más bajo del país: alquiler USD 100–200/mes'),
      li('Comida y servicios: muy económicos'),
      li('Rivera: podés acceder a precios y productos de Brasil fácilmente'),
      h3('Rivera: la ciudad fronteriza'),
      li('Rivera-Livramento (Brasil): ciudad gemela, libre circulación entre países'),
      li('Acceso a supermercados, electrónica y servicios de Brasil a precios en reales'),
      li('Comunidad billingüe (español-portugués) por influencia brasileña'),
      li('Conexión a Montevideo: 5–6h en ómnibus'),
      h3('Tacuarembó: la capital gaucha'),
      li('Hogar del Festival de Folklore del Uruguay, el más grande del país'),
      li('Según una teoría, cuna del tango (Carlos Gardel habría nacido aquí)'),
      li('Pesca en el Lago Artificial de Tacuarembó'),
      li('Estancias turísticas y turismo rural de calidad'),
      h3('Naturaleza y cultura'),
      li('Grutas del Palacio (Flores): formación geológica única'),
      li('Fuerte San Miguel: fortaleza histórica en la frontera con Brasil'),
      li('Carnaval de las Llamadas: fuerte tradición afro-uruguaya en Rivera'),
      h3('Conectividad'),
      p('Internet básica disponible en las ciudades principales. Las zonas rurales tienen cobertura limitada. Ideal para quienes no dependen de video calls de alta resolución.'),
    ],
    links: [],
  },
]

async function seed() {
  console.log(`Seeding ${places.length} places...`)
  for (const place of places) {
    try {
      await client.createOrReplace(place)
      console.log(`✓ ${place.title}`)
    } catch (err) {
      console.error(`✗ ${place.title}:`, err.message)
    }
  }
  console.log('Done.')
}

seed()
